export const ADD__TO__CART = 'ADD__TO__CART'
export const CHANGE__ITEM__QT = 'CHANGE__ITEM__QT'
export const REMOVE__ITEM__FROM__CART = 'REMOVE__ITEM__FROM__CART'
export const EXCLUDE__ITEM__FROM__CART = 'EXCLUDE__ITEM__FROM__CART'
export const BUY__PRODUCT = 'BUY__PRODUCT'
